server:
  port: 8085

spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:mysql://localhost:3308/inventory_db
    username: inventory_user
    password: inventory_pass

  jpa:
    hibernate:
      ddl-auto: update