server:
  port: 8083

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:mysql://localhost:3307/product_db
    username: product_user
    password: product_pass

  jpa:
    hibernate:
      ddl-auto: update
